### ISSUE TITLE
showing new labels in brackets

### ISSUE THREAD

**Issue by demontech** [JotaDF/moodle-block_grade_overview#10]
Hi there,

Installed the new version 2022071310, but now the new labels grade overview and report grade shows in brackets and also the help sections.

Running in Moodle 3.6 with php v7.0

![image](https://user-images.githubusercontent.com/8148238/214994575-6808960e-7503-405f-ac1f-cdc64c459e67.png)

![image](https://user-images.githubusercontent.com/8148238/214994655-bba63216-b922-4ddc-a44c-e7217a627b67.png)

![image](https://user-images.githubusercontent.com/8148238/214994734-50bc1dca-1485-46ed-a327-3122decb3a37.png)

Thank you for this great plugin!

**Comment by JotaDF** [comment]
Hi,
I will check and correct.

Thanks

**Comment by JotaDF** [comment]
I checked that these strings are in the translation file. Check if you need to update your language pack!

**Comment by demontech** [comment]
Hi Jose,

That worked ! ... weird. I just rewrite the same text on that string on the language customization and worked

Thank you!
