### ISSUE TITLE
language in completion report

### ISSUE THREAD

**Issue by demontech** [JotaDF/moodle-block_grade_overview#11]
Hi Jose,

I noticed that the word "Concluido" is showing on the completion report once is downloaded rather than "Completed". I'm using the English language.

![image](https://user-images.githubusercontent.com/8148238/216474636-95e96805-ed1b-41b6-81f1-3cd4bee027e3.png)

thank you for this great plugin!

**Comment by demontech** [comment]
Found the issue and fix it on line 86 of download.php file
![image](https://user-images.githubusercontent.com/8148238/216478532-bc576ef2-8171-475d-a233-5a86ef36bed7.png)

**Comment by JotaDF** [comment]
My mistake. I will correct.
Thanks for contributing!

**Comment by JotaDF** [comment]
I just uploaded a version to fix this!
Thanks
