### ISSUE TITLE
Better not to rely on site course id always equal to 1

### ISSUE THREAD

**Issue by mudrd8mz** [jotadf/moodle-block_grade_overview#2]
https://github.com/JotaDF/moodle-block_grade_overview/blob/2f8f6864b2bd4729f6b213e5bb8bd7b8d125e5b5/block_grade_overview.php#L81

It may be better to use `SITEID` constant here, instead of hard-coded 1.

**Comment by JotaDF** [comment]
Correction performed.
Thank you David
