### ISSUE TITLE
Functions in lib.php do not have prefix name

### ISSUE THREAD

**Issue by mudrd8mz** [jotadf/moodle-block_grade_overview#3]
The functions defined in lib.php are currently named such as:

```
function get_grade_atcvity($courseid, $userid, $iteminstance, $itemtype)
function get_count_atv_all($courseid, $iteminstance, $itemtype)
function count_studens_course($courseid)
function get_studens_course($courseid)
function count_studens_accessed_course($courseid)
function get_course_activities($courseid)
function compare_activities($a, $b)
function user_course_progress($user, $course)
function get_view_student($user, $course, $atvscheck, $calc, $decimalplaces, $desription, $showcheck, $shownameuser)
function get_view_editor($course, $instanceid, $atvscheck, $showcheck)
```

That is a problem as there are moments when all lib.php files from all plugins are loaded by the core. There could easily be a conflict with a core function of the same name.

For that reason, all plugins must prefix their function names - see https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions

**Comment by mudrd8mz** [comment]
p.s. this can be a good opportunity to fix some typos in the functions names such as "get_grade_atcvity" or "count_studens_course"

**Comment by JotaDF** [comment]
Correction performed.
Thank you David

**Comment by mudrd8mz** [comment]
I am afraid there was some misunderstanding here. Please read linked docs more carefully again. You added `grade_overview_` prefix to the functions names, but as the docs states:

> names must start with the plugin type and plugin name, as in `block_yourname_something`
