### ISSUE TITLE
block_grade_overview.php must not require login

### ISSUE THREAD

**Issue by mudrd8mz** [jotadf/moodle-block_grade_overview#4]
The login must not be required at the top global scope in the file, as it can be loaded anytime.

https://github.com/JotaDF/moodle-block_grade_overview/blob/2f8f6864b2bd4729f6b213e5bb8bd7b8d125e5b5/block_grade_overview.php#L28

**Comment by JotaDF** [comment]
Correction performed.
Thank you David
