### ISSUE TITLE
better to use != SITEID

### ISSUE THREAD

**Issue by danmarsden** [jotadf/moodle-block_grade_overview#7]
in #2 David mentioned that you should be using SITEID instead of hard-coding the value, but you've changed this to using a greater than check - it's possible (although highly unlikely) that a SITEID could end up as an arbitrary number eg "56" but you could still have a normal course with the value "6" - so it's better to use something like:
if ($courseid != SITEID) 
rather than a greater than sign.

**Comment by JotaDF** [comment]
Yes, I reviewed the code making this change. Thanks for helping me!
