### ISSUE TITLE
Grade overview report generates error when turning edit toggle on or off 

### ISSUE THREAD

**Issue by ecottis** [JotaDF/moodle-block_grade_overview#8]
looks good.  However when you toggle to turn editing on or off when viewing the Grade overview  report you get the following error:

![image](https://user-images.githubusercontent.com/67025862/177877272-3c78178f-423d-49fb-937e-5b0e002a44c2.png)

**Comment by JotaDF** [comment]
Thanks for reporting! I made the correction!

**Comment by ecottis** [comment]
Thanks just installed and working fine.  Thanks for developing this useful plug-in.
